# Generated by Django 5.0.14 on 2026-09-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categorias', models.AutoField(db_column='ID_categorias', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id_categorias'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compras', models.AutoField(db_column='ID_compras', primary_key=True, serialize=False)),
                ('precio_total', models.DecimalField(db_column='Precio_total', decimal_places=2, max_digits=9)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['id_compras'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleados', models.AutoField(db_column='ID_empleados', primary_key=True, serialize=False)),
                ('dni', models.IntegerField(db_column='DNI')),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('domicilio', models.CharField(db_column='Domicilio', max_length=200)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id_empleados'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_locales', models.AutoField(db_column='ID_locales', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('direccion', models.CharField(db_column='Direccion', max_length=200)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('red_social', models.CharField(db_column='Red_social', max_length=50)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'db_table': 'locales',
                'ordering': ['id_locales'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menus', models.AutoField(db_column='ID_menus', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('fecha_inicio', models.DateTimeField(db_column='Fecha_inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='Fecha_fin', null=True)),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'menus',
                'ordering': ['id_menus'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodos', models.AutoField(db_column='ID_metodos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'db_table': 'metodos_pago',
                'ordering': ['id_metodos'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_productos', models.AutoField(db_column='ID_productos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('precio_unitario', models.DecimalField(db_column='Precio_unitario', decimal_places=2, max_digits=9)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id_productos'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedores', models.AutoField(db_column='ID_proveedores', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('direccion', models.CharField(db_column='Direccion', max_length=200)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('cuit', models.CharField(db_column='CUIT', max_length=30)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['id_proveedores'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_roles', models.AutoField(db_column='ID_roles', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id_roles'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuarios', models.AutoField(db_column='ID_usuarios', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=30)),
                ('password', models.CharField(db_column='Password', max_length=30)),
                ('fecha_modificacion', models.DateTimeField(db_column='Fecha_modificacion')),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id_usuarios'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumos', models.AutoField(db_column='ID_insumos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('unidad', models.CharField(db_column='Unidad', max_length=10)),
                ('stock_actual', models.IntegerField(db_column='Stock_actual')),
                ('stock_minimo', models.IntegerField(db_column='Stock_minimo')),
                ('categoria', models.ForeignKey(db_column='ID_categorias', on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumos',
                'ordering': ['id_insumos'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalles_compras', models.AutoField(db_column='ID_detalles_compras', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=9)),
                ('compra', models.ForeignKey(db_column='ID_compras', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compra')),
                ('insumo', models.ForeignKey(db_column='ID_insumos', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compras', to='core.insumo')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
                'db_table': 'detalles_compras',
                'ordering': ['id_detalles_compras'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_cajas', models.AutoField(db_column='ID_cajas', primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(db_column='Fecha_apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, db_column='Fecha_cierre', null=True)),
                ('monto_apertura', models.DecimalField(db_column='Monto_apertura', decimal_places=2, max_digits=9)),
                ('monto_cierre', models.DecimalField(blank=True, db_column='Monto_cierre', decimal_places=2, max_digits=9, null=True)),
                ('estado', models.BooleanField(db_column='Estado')),
                ('local', models.ForeignKey(db_column='ID_locales', on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='core.local')),
                ('usuario', models.ForeignKey(db_column='ID_usuarios', on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
                'ordering': ['id_cajas'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo',
            field=models.ForeignKey(db_column='ID_metodos', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.metodopago'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedidos', models.AutoField(db_column='ID_pedidos', primary_key=True, serialize=False)),
                ('cliente', models.CharField(db_column='Cliente', max_length=50)),
                ('direccion', models.CharField(db_column='Direccion', max_length=200)),
                ('precio_total', models.DecimalField(db_column='Precio_total', decimal_places=2, max_digits=9)),
                ('estado', models.CharField(choices=[('Cancelado', 'Cancelado'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], db_column='Estado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
                ('empleado', models.ForeignKey(db_column='ID_empleados', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.empleado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['id_pedidos'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalles_pedidos', models.AutoField(db_column='ID_detalles_pedidos', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=9)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('pedido', models.ForeignKey(db_column='ID_pedidos', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
                ('producto', models.ForeignKey(db_column='ID_productos', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedidos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
                'db_table': 'detalles_pedidos',
                'ordering': ['id_detalles_pedidos'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id_detalles_menus', models.AutoField(db_column='ID_detalles_menus', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('descuento', models.IntegerField(db_column='Descuento')),
                ('menu', models.ForeignKey(db_column='ID_menus', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.menu')),
                ('producto', models.ForeignKey(db_column='ID_productos', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_menus', to='core.producto')),
            ],
            options={
                'verbose_name': 'Detalle de menú',
                'verbose_name_plural': 'Detalles de menú',
                'db_table': 'detalles_menus',
                'ordering': ['id_detalles_menus'],
            },
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('id_productos_insumos', models.AutoField(db_column='ID_productos_insumos', primary_key=True, serialize=False)),
                ('insumo', models.ForeignKey(db_column='ID_insumos', on_delete=django.db.models.deletion.CASCADE, related_name='productos_insumos', to='core.insumo')),
                ('producto', models.ForeignKey(db_column='ID_productos', on_delete=django.db.models.deletion.CASCADE, related_name='productos_insumos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Relación Producto-Insumo',
                'verbose_name_plural': 'Relaciones Producto-Insumo',
                'db_table': 'productos_x_insumos',
                'ordering': ['id_productos_insumos'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='ID_proveedores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('id_proveedores_insumos', models.AutoField(db_column='ID_proveedores_insumos', primary_key=True, serialize=False)),
                ('insumo', models.ForeignKey(db_column='ID_insumos', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_insumos', to='core.insumo')),
                ('proveedor', models.ForeignKey(db_column='ID_proveedores', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_insumos', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Relación Proveedor-Insumo',
                'verbose_name_plural': 'Relaciones Proveedor-Insumo',
                'db_table': 'proveedores_x_insumos',
                'ordering': ['id_proveedores_insumos'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(db_column='ID_usuarios', on_delete=django.db.models.deletion.DO_NOTHING, related_name='empleado', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuarios_roles', models.AutoField(db_column='ID_usuarios_roles', primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(db_column='ID_roles', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='core.rol')),
                ('usuario', models.ForeignKey(db_column='ID_usuarios', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Relación Usuario-Rol',
                'verbose_name_plural': 'Relaciones Usuario-Rol',
                'db_table': 'usuarios_x_roles',
                'ordering': ['id_usuarios_roles'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_ventas', models.AutoField(db_column='ID_ventas', primary_key=True, serialize=False)),
                ('precio_total', models.DecimalField(db_column='Precio_total', decimal_places=2, max_digits=9)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
                ('metodo', models.ForeignKey(db_column='ID_metodo', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.metodopago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id_ventas'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimientos', models.AutoField(db_column='ID_movimientos', primary_key=True, serialize=False)),
                ('concepto', models.CharField(db_column='Concepto', max_length=50)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=9)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_creacion')),
                ('caja', models.ForeignKey(db_column='ID_cajas', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.caja')),
                ('compra', models.ForeignKey(blank=True, db_column='ID_compras', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='core.compra')),
                ('venta', models.ForeignKey(blank=True, db_column='ID_ventas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='core.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'db_table': 'movimientos_caja',
                'ordering': ['id_movimientos'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalles_ventas', models.AutoField(db_column='ID_detalles_ventas', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=9)),
                ('producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ventas', to='core.producto')),
                ('venta', models.ForeignKey(db_column='ID_Ventas', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'detalles_ventas',
                'ordering': ['id_detalles_ventas'],
            },
        ),
    ]
