# Generated by Django 5.0.14 on 2026-09-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoinsumo',
            options={'ordering': ['id_productos_insumos'], 'verbose_name': 'Producto-Insumo', 'verbose_name_plural': 'Productos-Insumos'},
        ),
        migrations.AlterModelOptions(
            name='proveedorinsumo',
            options={'ordering': ['id_proveedores_insumos'], 'verbose_name': 'Proveedor-Insumo', 'verbose_name_plural': 'Proveedores-Insumos'},
        ),
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'ordering': ['id_usuarios_roles'], 'verbose_name': 'Usuario-Rol', 'verbose_name_plural': 'Usuarios-Roles'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='local',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion'),
        ),
    ]
